# Generated by Django 4.0.4 on 2022-05-18 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_document_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
