# Generated by Django 4.0.4 on 2022-05-18 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_document_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='time',
            new_name='created',
        ),
    ]
